config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  root :to => 'home#index'

  resources :users, only: [:show, :new, :create]
  resources :user_sessions, only: [:new, :create, :destroy]

  get 'me' => 'me#index'
  post 'oauth_login/callback' => 'oauth_logins#callback'
  get 'oauth_login/callback' => 'oauth_logins#callback' # for use with Github, Facebook
  get 'oauth_login/:provider' => 'oauth_logins#oauth', :as => :auth_at_provider

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end

  has_many :authentications, :dependent => :destroy
  accepts_nested_attributes_for :authentications

  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :require_login

  def not_authenticated
    redirect_to login_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/me_controller.rb
class MeController < ApplicationController
  skip_before_action :require_login
  skip_before_action :verify_authenticity_token
  before_action :doorkeeper_authorize!

  def index
    render json: { id: current_user.id, email: current_user.email }
  end

private

  def current_user
    if doorkeeper_token
      @current_user ||= User.find(doorkeeper_token.resource_owner_id)
    end
  end
end

app/controllers/oauth_logins_controller.rb
class OauthLoginsController < ApplicationController
  skip_before_action :require_login

  def oauth
    # session[:return_to_url] = request.referer unless request.referer =~ /oauth/
    login_at(params[:provider])
  end

  def callback
    provider = params[:provider]
    return_to = session['return_to_url']
    if @user = login_from(provider)
      redirect_to return_to || user_url(@user, :notice => "Logged in from #{provider.titleize}!")
    else
      begin
        @user = create_from(provider)
        # NOTE: this is the place to add '@user.activate!' if you are using user_activation submodule

        reset_session # protect from session fixation attack
        auto_login(@user)
        redirect_to return_to || user_url(@user, :notice => "Logged in from #{provider.titleize}!")
      rescue Error => e
        redirect_to login_url, :alert => "Failed to login from #{provider.titleize}!"
      end
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(user_url @user, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(login_url, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update]

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      auto_login(@user)
      redirect_back_or_to user_url @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params
      .require(:user)
      .permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/me_helper.rb
module MeHelper
end

app/helpers/oauth2_helper.rb
module Oauth2Helper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.slim
p
  strong
    ' Id:
  = current_user.id
p
  strong
    ' Email:
  = current_user.email

app/views/layouts/application.html.slim
doctype html
html
  head
    title TeachbaseAuth
    = csrf_meta_tags

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    - if current_user
      .menu
        = link_to 'Logout', :logout, method: :post
    = yield

app/views/user_sessions/_form.html.slim
= form_tag user_sessions_path, method: :post do
  .field
    = label_tag :email
    br
    = text_field_tag :email
  .field
    = label_tag :password
    br
    = password_field_tag :password
  .actions
    = submit_tag 'Login'

app/views/user_sessions/_oauth_providers.html.slim
.b-oauth
  = link_to 'Facebook', auth_at_provider_url(provider: :facebook)

app/views/user_sessions/create.html.slim
h1 UserSessions#create
p Find me in app/views/user_sessions/create.html.slim

app/views/user_sessions/destroy.html.slim
h1 UserSessions#destroy
p Find me in app/views/user_sessions/destroy.html.slim

app/views/user_sessions/new.html.slim
h1 Login
= render 'form'
= link_to 'Register', new_user_url
= render 'oauth_providers'

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.text_field :password
  .field
    = f.label :password_confirmation
    = f.text_field :password_confirmation
  .actions = f.submit

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

= link_to 'Show', @user
'|
= link_to 'Back', users_path

app/views/users/index.html.slim
h1 Listing users

table
  thead
    tr
      th Email
      th Crypted password
      th Salt
      th
      th
      th

  tbody
    - @users.each do |user|
      tr
        td = user.email
        td = user.crypted_password
        td = user.salt
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Login', login_url
= render 'user_sessions/oauth_providers'

app/views/users/show.html.slim
p#notice = notice

p
  strong Email:
  = @user.email